### ISSUE TITLE
[Feature] 添加数据导出功能

### ISSUE THREAD

**Issue by yukonisen** [dmzz-yyhyy/LightNovelReader#116]
### What new features do you want? - 你想要什么新功能？

对于 #114 的数据格式支持导出
输出的文件应具有辨识度的后缀名，并且支持重新导入

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by MagicHuaGi** [comment]
Failed to load in.
