### ISSUE TITLE
[Feature] 增加探索页面下拉刷新功能

### ISSUE THREAD

**Issue by Qing-Novel** [dmzz-yyhyy/LightNovelReader#118]
### What new features do you want? - 你想要什么新功能？

有时候网络不太好会导致探索页面刷新不出来内容，此时只能通过重启软件让内容刷新出来，如果增加下拉刷新功能就可以避免重启软件刷新内容

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by dmzz-yyhyy** [comment]
您好，首先抱歉因为学业问题，现在才予以回复。
可以详细描述一下你指的探索页是具体的哪个页面吗？
还有，软件对于是否联网的判断是间隔时间自动重试，目前的默认设定是5秒。
如果需要下拉刷新的话具体有哪些内容需要添加呢？

**Comment by Qing-Novel** [comment]
这个页面的首页、全部、分类建议都加下拉刷新
![Screenshot_20241025_221555_indi dmzz_yyhyy lightnovelreader](https://github.com/user-attachments/assets/d935f330-3c8a-4ba9-8076-2b4ef05dbd29)

**Comment by dmzz-yyhyy** [comment]
您回复的挺快的倒是。。。
我们了解此需求了，并且会计划在1.0.0版本中实现

**Comment by Qing-Novel** [comment]
> 您回复的挺快的倒是。。。 我们了解此需求了，并且会计划在1.0.0版本中实现

回复快主要是有邮箱提醒
好的好的，麻烦了
