### ISSUE TITLE
[Feature] 仿实体书翻页功能

### ISSUE THREAD

**Issue by woniu163** [dmzz-yyhyy/LightNovelReader#41]
### What new features do you want? - 你想要什么新功能？

我看到一个这样的库[PTQFlipper](https://github.com/FantasticPornTaiQiang/PTQFlipper)，刚好是基于compose实现的，如果能集成到项目中，一定很有意思

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by dmzz-yyhyy** [comment]
好东西，我们会在未来版本集成改功能

**Comment by dmzz-yyhyy** [comment]
![image](https://github.com/user-attachments/assets/4f410db3-ed37-486c-bc2b-903f39e89614)
由于过于糟糕的使用体验，我们将拒绝集成该库，但我们仍然会加入翻页模式
