### ISSUE TITLE
[Bug] 一些 UI 错误

### ISSUE THREAD

**Issue by yukonisen** [dmzz-yyhyy/LightNovelReader#54]
### Version Details - 版本信息

latest - 0.4.1

### Existing behavior - 现有行为

![Screenshot_20240803-010728_LightNovelReader](https://github.com/user-attachments/assets/48760e8f-4b1c-4e72-857b-776b94331568)
导航栏间距

![Screenshot_20240803-010933_LightNovelReader](https://github.com/user-attachments/assets/7a9a0fcc-2b1d-4472-acc4-6832357e4041)
内容

![Screenshot_20240803-082821_LightNovelReader](https://github.com/user-attachments/assets/cf0a5df0-dcb3-4b62-91a2-7e61f66b126e)
行距、控件错位

### Expected behavior - 预期行为

rt

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by dmzz-yyhyy** [comment]
so what's the meaning of "rt"
